source "https://rubygems.org"

ruby "2.7.1"

gem "rails"
gem "pg"
gem "puma"
gem "slim-rails"
gem "dotenv-rails"
gem "sassc"
gem "turbolinks"
gem "bcrypt"
gem "rails-i18n"
gem "omniauth-facebook"
gem "byebug"
gem "down"
gem "listen"
gem "webpacker"
gem "babel-transpiler"
gem "font-awesome-sass"
gem "cancancan"
gem "friendly_id"
gem "activeadmin"
gem "paper_trail"
gem "bugsnag"
gem "sprockets", "3.7.2" # https://github.com/sass/sassc-rails/issues/122
gem "mini_magick"
gem "image_processing"

group :development do
  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rbenv"
  gem "capistrano3-puma"
end
