source "https://rubygems.org"

gem "rails"
gem "pg"
gem "puma"
gem "slim-rails"
gem "dotenv-rails"
gem "sassc"
gem "turbolinks"
gem "bcrypt"
gem "rails-i18n"
gem "omniauth-facebook"
gem "byebug"
gem "down"
gem "listen"
gem "webpacker"
gem "babel-transpiler"
gem "font-awesome-sass"

group :development do
  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rbenv"
  gem "capistrano3-puma"
end
